# modules/firewall_policy_conf/variables.tf

variable "firewall_policy_name" {
  description = "Name for the Network Firewall Policy."
  type        = string
}

variable "environment" {
  description = "The environment tag (e.g., dev, prod)."
  type        = string
}

# --- 5-Tuple Rule Group Inputs ---
variable "five_tuple_rg_capacity" {
  description = "Capacity for the 5-Tuple Stateful Rule Group."
  type        = number
}

variable "five_tuple_rules_string" {
  description = "Suricata-compatible rule string for 5-Tuple Rule Group."
  type        = string
}

# --- Domain Rule Group (FQDN) Inputs ---
variable "domain_rg_capacity" {
  description = "Capacity for the Domain List Rule Group."
  type        = number
}

# to receive the list of FQDNs generated by the root main.tf's CSV decoder
variable "allowed_domains_list" {
  description = "List of allowed FQDNs for the Domain Rule Group."
  type        = list(string)
}

# to handles complex list of objects structure for the rules in tfvars
# variable "domain_rules" {
#   description = "Structured list of rules for the Domain Rule Group."
#   type        = list(any)
#   default = []
# }

variable "stateful_rule_group_arns" {
  description = "List of ARNs for stateful rule groups"
  type        = list(string)
}

# variable "domain_rules" {
#   description = "A list of complex objects defining the stateful rules for FQDN filtering."
#   type = list(object({
#     priority = number
#     action   = string
#     protocol = string
#     source   = string
#     source_port = string
#     destination = string
#     destination_port = string
#     direction = string
#     rule_options = list(object({
#       keyword  = string
#       settings = list(string)
#     }))
#   }))
#   default = []
# }